name: Build Project and push to docker

on:
  push:
    branches:
      - "main"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # checkout the correct branch name
          fetch-depth: 0 # fetch the whole repo history

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: api-version
        with:
          proj-path: ./komikaan.Harvester/komikaan.Harvester.csproj

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{steps.api-version.outputs.version}}
          release_name: Release ${{steps.api-version.outputs.version}}
          draft: false
          prerelease: false

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: komikaan.Harvester/Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=enes1/komikaan-harvester:latest
          cache-to: type=inline
          tags: |
            enes1/komikaan-harvester:latest
            enes1/komikaan-harvester:${{steps.api-version.outputs.version}}
